apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::123456789012:user/john-doe
      username: john-doe
      groups:
        - system:masters
    - userarn: arn:aws:iam::123456789012:user/jane-smith
      username: jane-smith
      groups:
        - system:basic-user
  mapRoles: |
    - rolearn: arn:aws:iam::087657543526:role/SSOArquitectura-Asumed
      username: franco.navarro@orion.global
      groups:
        - system:masters